### ISSUE TITLE
Flea Player sale prices cache not being updated

### ISSUE THREAD

**Issue by BluBb-mADe** [DrakiaXYZ/SPT-LiveFleaPrices#1]
From what I can tell the game generates the data for average prices at which bots buy items on the flea and caches it but this mod doesn't appear to actually update this cache.
The relevant sections are as follows in the RagfairPriceService.ts
```ts
    /**
     * Generate static (handbook) and dynamic (prices.json) flea prices, store inside class as dictionaries
     */
    public async onLoad(): Promise<void>
    {
        if (!this.generatedStaticPrices)
        {
            this.generateStaticPrices();
            this.generatedStaticPrices = true;
        }

        if (!this.generatedDynamicPrices)
        {
            this.generateDynamicPrices();
            this.generatedDynamicPrices = true;
        }
    }
    /* .... */
    public generateStaticPrices(): void
    {
        for (
            const item of Object.values(this.databaseServer.getTables().templates.items).filter((x) =>
                x._type === "Item"
            )
        )
        {
            this.prices.static[item._id] = Math.round(this.handbookHelper.getTemplatePrice(item._id));
        }
    }
    protected generateDynamicPrices(): void 
    /* .... */
```

You can see that it caches the data that is used later to calculate the buy probability of the bot buy mechanism in `.static` properties.
To fix this issue I think all that is needed is to load the RagfairPriceService and manually call these two functions again after each update like this in mod.ts:
```ts
        const ragfairPriceService = Mod.container.resolve<RagfairPriceService>("RagfairPriceService");
        ragfairPriceService.generateStaticPrices();
        ragfairPriceService.generateDynamicPrices();
        logger.info("Flea Prices Updated!");
```

I have added this to my local mod.ts and it seems to work. At least its not causing any errors while still printing the price update message.

I might be totally missing something but I am not familiar with either code base to properly and conclusively test this myself.
So maybe this is entirely unnecessary and a placebo but when playing it feels like items are being bought by bots more in accordance to their average price this way.

**Comment by DrakiaXYZ** [comment]
Interesting, good catch on this one. I had only tested listed offers, not selling on the flea.

I'll get this fixed for the next version!

**Comment by DrakiaXYZ** [comment]
The new version should resolve this :) Thanks for letting me know about it!
