### ISSUE TITLE
Fetch error intermittently on startup

### ISSUE THREAD

**Issue by Jernee** [DrakiaXYZ/SPT-LiveFleaPrices#2]
Getting this error one startup intermittently.

ModLoader: Error when loading async mod: fetch failed
TypeError: fetch failed
at node:internal/deps/undici/undici:12345:11
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Function.updatePrices (/opt/server/user/mods/DrakiaXYZ-LiveFleaPrices/src/mod.ts:60:30)
at Mod.postDBLoadAsync (/opt/server/user/mods/DrakiaXYZ-LiveFleaPrices/src/mod.ts:37:14)
at PostDBModLoader.executeModsAsync (/snapshot/src/loaders/PostDBModLoader.ts:63:21)
at PostDBModLoader.onLoad (/snapshot/src/loaders/PostDBModLoader.ts:31:13)
at App.load (/snapshot/src/utils/App.ts:58:13)

**Comment by DrakiaXYZ** [comment]
Generally this would be caused by a connection issue between your PC and GitHub's CDN, not the mod itself. 

However the next time I release an update, I will look into adding a bit more handling around when this happens, to fall back to the last fetched prices

**Comment by Jernee** [comment]
> Generally this would be caused by a connection issue between your PC and GitHub's CDN, not the mod itself.
> 
> However the next time I release an update, I will look into adding a bit more handling around when this happens, to fall back to the last fetched prices

Running the server on a docker container on my dedicated server. It's in a data center down in Virginia so I'd find it hard to believe it's got bad connection. Is there some sort of timeout option I can change that would give it some more time to look or should I just wait for an update?

**Comment by Jernee** [comment]
After a talk with my server host I discovered they are using a temporary ddos protection method that was causing a problem with packet sizes causing the fetch to fail. Either way I forked the repository and made a version that retries the fetch a couple times so I could get around the problem.
